# Generated by Django 5.2.6 on 2025-09-09 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='running', max_length=20)),
            ],
            options={
                'db_table': 'log_analyses',
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_lines', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'log_files',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='LogFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField()),
                ('rule_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='logs.loganalysis')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
            options={
                'db_table': 'log_findings',
                'indexes': [models.Index(fields=['severity'], name='log_finding_severit_931ca4_idx'), models.Index(fields=['rule_name'], name='log_finding_rule_na_42617b_idx'), models.Index(fields=['created_at'], name='log_finding_created_b9d6ed_idx')],
            },
        ),
    ]
