# Generated by Django 5.2.6 on 2025-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
